version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: dbase_1
    volumes:
      - ./database:/var/lib/mysql
    expose:
      - 3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      - fullstack-app-network

  # EQC APP **************************
  todo-tool:
    image: todo-tool:latest
    container_name: todo-tool
    expose:
      - ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      # Uncomment following lines to use application-local.
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_PORT=${MYSQL_PORT}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "SERVER_PORT=${SERVER_PORT}"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - fullstack-app-network
  todo-react:
    image: u1810006/todo-tool:0.0.1-SNAPSHOT
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - todo-tool
    networks:
      - fullstack-app-network

networks:
  fullstack-app-network: